ARG PYTHON_VERSION="3.14"

FROM python:${PYTHON_VERSION}-slim

RUN apt-get update && \
    apt-get install -y \
      default-libmysqlclient-dev \
      build-essential \
      pkg-config

RUN pip install tox setuptools

WORKDIR /home

COPY parviraptor/ /home/parviraptor/
COPY tests/ /home/tests/
COPY *.* /home/

RUN python setup.py install
