[tox]
minversion = 4.0
skipsdist = false
skip_missing_interpreters = true
envlist =
    unittests-{dj40,dj41}-mysql{80,84,97}-py312
    unittests-{dj42,dj50,dj51,dj52,dj60}-mysql{80,84,97}-py313
    unittests-{dj52,dj60}-mysql{80,84,97}-py314

[testenv]
usedevelop = true
deps =
    django-app-helper
    packaging
    mysqlclient
    wait-for-it
    dj40: Django==4.0
    dj41: Django==4.1
    dj42: Django==4.2
    dj50: Django==5.0
    dj51: Django==5.1
    dj52: Django==5.2
    dj60: Django==6.0
changedir = {toxinidir}
commands =
    mysql80: wait-for-it --service mysql80:3306 --timeout 30
    mysql84: wait-for-it --service mysql84:3306 --timeout 30
    mysql97: wait-for-it --service mysql97:3306 --timeout 30

    django-app-helper parviraptor test {posargs} --extra-settings=tests/settings.py
passenv =
    DB_NAME
    DB_USER
    DB_PASSWORD
setenv =
    mysql80: DB_HOST=mysql80
    mysql84: DB_HOST=mysql84
    mysql97: DB_HOST=mysql97
