[tox]
minversion = 3.18
skipsdist = false
envlist =
    unittests
    flake8
    isort

[testenv:unittests]
basepython = python3
usedevelop = true
deps =
    django-app-helper
changedir = {toxinidir}
commands =
    django-app-helper parviraptor test \
        --extra-settings=parviraptor/tests/settings.py

[testenv:flake8]
basepython = python3
usedevelop = true
deps = flake8
changedir = {toxinidir}
commands = {envpython} -m flake8 .

[testenv:isort]
basepython = python3
usedevelop = true
deps = isort
changedir = {toxinidir}
commands = {envpython} -m isort . --check-only --diff
