#!/usr/bin/env bash

 if [[ $(date "+%m") == "12" ]]; then
   cat $(dirname $0)/parviraptor-12.txt
 else
   cat $(dirname $0)/parviraptor.txt
 fi

# Wir können hier nicht `set -o errexit` verwenden, weil wir sonst bei
# fehlschlagenden Testläufen sofort nach `docker-compose run` abbrechen
# würden und dann auf Dauer viele verwaiste Container liegen bleiben.

exit_status=0

docker_compose="docker compose -f $(dirname $0)/run-tests.compose.yaml"

$docker_compose up -d mysql80
$docker_compose up -d mysql84
$docker_compose up -d mysql97

for python_version in "3.12" "3.13" "3.14"; do
  echo "===== BUILDING WITH PYTHON $python_version"

  docker build . \
    --build-arg PYTHON_VERSION=$python_version \
    -f Dockerfile.tests \
    -t parviraptor-unittests || exit 1


  $docker_compose run --rm test tox $@

  if [ "$?" -ne 0 ]; then
    exit_status=1
  fi

done

$docker_compose down --volumes --remove-orphans

exit $exit_status
