# Generated by Django 3.2.3 on 2021-09-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("SQUASHED", "Squashed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=32,
                    ),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("a", models.IntegerField()),
                ("b", models.IntegerField()),
                ("result", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
