# Generated by Django 3.2.3 on 2021-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parviraptor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummyjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSING", "Processing"),
                    ("PROCESSED", "Processed"),
                    ("SQUASHED", "Squashed"),
                    ("FAILED", "Failed"),
                    ("IGNORED", "Ignored"),
                ],
                db_index=True,
                default="NEW",
                max_length=32,
            ),
        ),
    ]
