# Generated by Django 3.2.3 on 2021-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parviraptor", "0002_alter_dummyjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dummyjob",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
